version: '3'
services:
    olog-server:
        container_name: olog-server
        image: lnlscon/olog-server:latest
        hostname: olog-server
        environment:
            - ADMIN_PASSWORD=controle
            - CERTIFICATE_PASSWORD=controle
            - DB_USER=lnls_olog_user
            - DB_PASSWORD=controle
            - DB_NAME=olog
            - REALM_SEARCH_BIND_DN=CN=***bind_dn***
            - REALM_SEARCH_BIND_PASS=***bind_dn_passwd***
            - REALM_SEARCH_FILTER="sAMAccountName=%s"
            - REALM_BASE_DN="OU=Users,OU=LNLS,DC=abtlus,DC=org,DC=br"
            - REALM_URL="ldap://ad1.abtlus.org.br:389"
        ports:
            - "4848:4848"
            - "8181:8181"
            - "1527:1527"
        networks:
            olog-network:
                ipv4_address: 192.168.7.2
        dns:
            - 10.0.0.71
            - 10.0.0.72
        depends_on:
            - olog-mysql-db
        volumes:
            - /storage/olog/data/:/glassfish4/glassfish/domains/domain1/config/jackrabbit/

    olog-mysql-db:
        container_name: olog-mysql-db
        image: lnlscon/olog-mysql-db:latest
        hostname: olog-mysql-db
        environment:
            - MYSQL_USER=lnls_olog_user
            - MYSQL_ROOT_PASSWORD=controle
            - MYSQL_PASSWORD=controle
            - MYSQL_DATABASE=olog
            - PGDATA=/var/lib/postgresql/data/olog-db
        networks:
            olog-network:
                ipv4_address: 192.168.7.3
        dns:
            - 10.0.0.71
            - 10.0.0.72
        volumes:
            - /storage/olog/db:/var/lib/mysql

    # olog-postgres-db:
    #     container_name: olog-postgres-db
    #     image: gciotto/olog-postgres-db
    #     hostname: olog-postgres-db
    #     environment:
    #         - POSTGRES_USER=lnls_olog_user
    #         - POSTGRES_PASSWORD=controle
    #         - POSTGRES_DB=olog
    #         - PGDATA=/var/lib/postgresql/data/olog-db
    #     networks:
    #         olog-network:
    #             ipv4_address: 192.168.7.3
    #     dns:
    #         - 10.0.0.71
    #         - 10.0.0.72
    #     volumes:
    #         - /home/opr24/docker-storage/olog-db:/var/lib/postgresql/data/olog-db

networks:
    olog-network:
        ipam:
            config:
                - subnet: 192.168.7.0/24
