version: '3.2'
services:
    olog-server:
        hostname: olog-server
        image: lnlscon/olog-server:latest
        environment:
            - ADMIN_PASSWORD=controle
            - CERTIFICATE_PASSWORD=controle
            - DB_USER=lnls_olog_user
            - DB_PASSWORD=controle 
            - DB_NAME=olog 
            - REALM_SEARCH_BIND_DN=***bind_dn***
            - REALM_SEARCH_BIND_PASS=***bind_dn_passwd***
            - REALM_SEARCH_FILTER="sAMAccountName=%s"
            - REALM_BASE_DN="OU=Users,OU=LNLS,DC=abtlus,DC=org,DC=br"  
            - REALM_URL="ldap://ad1.abtlus.org.br:389"
        ports:
            - "4848:4848"
            - "8181:8181"
            - "1527:1527"
        networks:
            - olog-network
        dns:
            - 10.0.0.71
            - 10.0.0.72
        depends_on:
            - olog-mysql-db
        volumes:
            - /storage/olog/data/:/glassfish4/glassfish/domains/domain1/config/jackrabbit/
        deploy:
            resources:
              limits:
                cpus: "4"
                memory: 4096M

    olog-mysql-db:
        hostname: olog-mysql-db
        image: lnlscon/olog-mysql-db:latest
        environment:
            - MYSQL_USER=lnls_olog_user
            - MYSQL_ROOT_PASSWORD=controle
            - MYSQL_PASSWORD=controle
            - MYSQL_DATABASE=olog
            - PGDATA=/var/lib/postgresql/data/olog-db
        networks:
            - olog-network
        dns:
            - 10.0.0.71
            - 10.0.0.72
        volumes:
            - /storage/olog/db:/var/lib/mysql
        deploy:
            resources:
              limits:
                cpus: "0.5"
                memory: 512M

    # olog-postgres-db:
    #     container_name: olog-postgres-db
    #     image: gciotto/olog-postgres-db
    #     hostname: olog-postgres-db
    #     environment:
    #         - POSTGRES_USER=lnls_olog_user
    #         - POSTGRES_PASSWORD=controle
    #         - POSTGRES_DB=olog
    #         - PGDATA=/var/lib/postgresql/data/olog-db
    #     networks:
    #         - olog-network
    #     dns:
    #         - 10.0.0.71
    #         - 10.0.0.72
    #     volumes:
    #         - /home/opr24/docker-storage/olog-db:/var/lib/postgresql/data/olog-db

networks:
    olog-network:
        ipam:
            config:
                - subnet: 192.168.7.0/24
